/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as FormulasRouteImport } from './routes/formulas'
import { Route as EdubotRouteImport } from './routes/edubot'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUnitsRouteImport } from './routes/admin.units'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminPdfsRouteImport } from './routes/admin.pdfs'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulasRoute = FormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const EdubotRoute = EdubotRouteImport.update({
  id: '/edubot',
  path: '/edubot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnitsRoute = AdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPdfsRoute = AdminPdfsRouteImport.update({
  id: '/pdfs',
  path: '/pdfs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/edubot': typeof EdubotRoute
  '/formulas': typeof FormulasRoute
  '/notes': typeof NotesRoute
  '/papers': typeof PapersRoute
  '/videos': typeof VideosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/pdfs': typeof AdminPdfsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/units': typeof AdminUnitsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/edubot': typeof EdubotRoute
  '/formulas': typeof FormulasRoute
  '/notes': typeof NotesRoute
  '/papers': typeof PapersRoute
  '/videos': typeof VideosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/pdfs': typeof AdminPdfsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/units': typeof AdminUnitsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/edubot': typeof EdubotRoute
  '/formulas': typeof FormulasRoute
  '/notes': typeof NotesRoute
  '/papers': typeof PapersRoute
  '/videos': typeof VideosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/pdfs': typeof AdminPdfsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/units': typeof AdminUnitsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/edubot'
    | '/formulas'
    | '/notes'
    | '/papers'
    | '/videos'
    | '/admin/analytics'
    | '/admin/pdfs'
    | '/admin/subjects'
    | '/admin/units'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/edubot'
    | '/formulas'
    | '/notes'
    | '/papers'
    | '/videos'
    | '/admin/analytics'
    | '/admin/pdfs'
    | '/admin/subjects'
    | '/admin/units'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/edubot'
    | '/formulas'
    | '/notes'
    | '/papers'
    | '/videos'
    | '/admin/analytics'
    | '/admin/pdfs'
    | '/admin/subjects'
    | '/admin/units'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  EdubotRoute: typeof EdubotRoute
  FormulasRoute: typeof FormulasRoute
  NotesRoute: typeof NotesRoute
  PapersRoute: typeof PapersRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulas': {
      id: '/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof FormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edubot': {
      id: '/edubot'
      path: '/edubot'
      fullPath: '/edubot'
      preLoaderRoute: typeof EdubotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/units': {
      id: '/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AdminUnitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pdfs': {
      id: '/admin/pdfs'
      path: '/pdfs'
      fullPath: '/admin/pdfs'
      preLoaderRoute: typeof AdminPdfsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminPdfsRoute: typeof AdminPdfsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminUnitsRoute: typeof AdminUnitsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminPdfsRoute: AdminPdfsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminUnitsRoute: AdminUnitsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  EdubotRoute: EdubotRoute,
  FormulasRoute: FormulasRoute,
  NotesRoute: NotesRoute,
  PapersRoute: PapersRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
